/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator_amqp.rb

package com.trafigura.tradecapture.internal.permissionservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import com.trafigura.tradinghub.services.discovery.ServiceAdvertisement
import org.jboss.resteasy.client._

class AMQPDesktopPermissionServiceLocator(ch:ConnectorHolder) extends AbstractServiceLocator[DesktopPermissionService](ch) with DesktopPermissionServiceLocator {
  def serviceKey = "DesktopPermissionService"

  def createProxy(advertisement:ServiceAdvertisement):DesktopPermissionService =
    new DesktopPermissionServiceResourceProxy(ProxyFactory.create(classOf[DesktopPermissionServiceResource], advertisement.address))
}

class AMQPLocatableDesktopPermissionService(ch:ConnectorHolder)
  extends LocatableDesktopPermissionService(new AMQPDesktopPermissionServiceLocator(ch))