/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service.rb

package com.trafigura.tradecapture.internal.permissionservice

import com.trafigura.tradecapture.internal.permissionservice._

import com.trafigura.tradinghub.support._
import org.codehaus.jettison.json.JSONObject
import com.trafigura.tradinghub.support._


/**
 * /// Group Management Service
 */

trait GroupService extends ModelService {
  override def serviceNames = super.serviceNames ++ Seq("GroupService")
  override def serviceKeys = super.serviceKeys ++ Seq("GroupService")

  
    def create(group: com.trafigura.tradecapture.internal.permissionservice.Group): com.trafigura.tradecapture.internal.permissionservice.PermissionResult
  
    def get(oid: Int): com.trafigura.tradecapture.internal.permissionservice.Group
  
    def getAll(): List[com.trafigura.tradecapture.internal.permissionservice.Group]
  
    def update(group: com.trafigura.tradecapture.internal.permissionservice.Group): com.trafigura.tradecapture.internal.permissionservice.PermissionResult
  
    def delete(oid: Int): Boolean
  
    def addUser(groupOid: Int, userOid: Int): Boolean
  
    def removeUser(groupOid: Int, userOid: Int): Boolean
  
    def getGroupUsers(oid: Int): List[com.trafigura.tradecapture.internal.permissionservice.User]
  
    def getGroupRoles(oid: Int): List[com.trafigura.tradecapture.internal.permissionservice.Role]
  
    def addRole(groupOid: Int, roleOid: Int): Boolean
  
    def removeRole(groupOid: Int, roleOid: Int): Boolean
  
}
