/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service.rb

package com.trafigura.tradecapture.internal.permissionservice

import com.trafigura.tradecapture.internal.permissionservice._

import com.trafigura.tradinghub.support._
import org.codehaus.jettison.json.JSONObject
import com.trafigura.tradinghub.support._


/**
 * // This is the Permission service interface
/// Permission Management Service
 */

trait PermissionService extends ModelService {
  override def serviceNames = super.serviceNames ++ Seq("PermissionService")
  override def serviceKeys = super.serviceKeys ++ Seq("PermissionService")

  
    def getAll(): List[com.trafigura.tradecapture.internal.permissionservice.Permission]
  
    def getAllUser(sid: String): List[com.trafigura.tradecapture.internal.permissionservice.Permission]
  
    def getEffective(sid: String, requiredPermissions: List[com.trafigura.tradecapture.internal.permissionservice.Permission]): List[com.trafigura.tradecapture.internal.permissionservice.Permission]
  
    def checkPermission(sid: String, requiredPermissions: List[com.trafigura.tradecapture.internal.permissionservice.Permission]): Boolean
  
    def checkPermissionForRequester(requiredPermissions: List[com.trafigura.tradecapture.internal.permissionservice.Permission]): Boolean
  
    def create(permission: com.trafigura.tradecapture.internal.permissionservice.Permission): com.trafigura.tradecapture.internal.permissionservice.Permission
  
    def delete(permission: com.trafigura.tradecapture.internal.permissionservice.Permission): Boolean
  
}
