/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service.rb

package com.trafigura.tradecapture.internal.permissionservice

import com.trafigura.tradecapture.internal.permissionservice._

import com.trafigura.tradinghub.support._
import org.codehaus.jettison.json.JSONObject
import com.trafigura.tradinghub.support._


/**
 * /// User Management Service
 */

trait UserService extends ModelService {
  override def serviceNames = super.serviceNames ++ Seq("UserService")
  override def serviceKeys = super.serviceKeys ++ Seq("UserService")

  
    def create(user: com.trafigura.tradecapture.internal.permissionservice.User): com.trafigura.tradecapture.internal.permissionservice.PermissionResult
  
    def getBySid(sid: String): com.trafigura.tradecapture.internal.permissionservice.User
  
    def getByUserId(userId: com.trafigura.tradecapture.internal.permissionservice.UserId): com.trafigura.tradecapture.internal.permissionservice.User
  
    def get(oid: Int): com.trafigura.tradecapture.internal.permissionservice.User
  
    def tryGet(oid: Int): List[com.trafigura.tradecapture.internal.permissionservice.User]
  
    def getAll(): List[com.trafigura.tradecapture.internal.permissionservice.User]
  
    def update(user: com.trafigura.tradecapture.internal.permissionservice.User): com.trafigura.tradecapture.internal.permissionservice.PermissionResult
  
    def delete(oid: Int): Boolean
  
    def addRole(userOid: Int, roleOid: Int): Boolean
  
    def removeRole(userOid: Int, roleOid: Int): Boolean
  
    def getUserRoles(oid: Int): List[com.trafigura.tradecapture.internal.permissionservice.Role]
  
    def getUserGroups(oid: Int): List[com.trafigura.tradecapture.internal.permissionservice.Group]
  
    def getUserGroupRoles(oid: Int): List[com.trafigura.tradecapture.internal.permissionservice.Role]
  
}
