/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.permissionservice





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._



/**
 explicit many to many mapping tables
ideally the binding-gen dsl would support this but it needs implementing
 */


 class UserRoles extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var oid:Int = 0
    
    
    

var userId:Int = 0
    
    
    

var roleId:Int = 0
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.permissionservice.UserRoles]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.permissionservice.UserRoles]
            that.canEqual(this) && this.oid == that.oid && this.roleId == that.roleId && this.userId == that.userId &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.permissionservice.UserRoles]

  override def hashCode = {
    (41 * (41 * (41 *  1
    ) +
         oid.hashCode
        
    ) +
         roleId.hashCode
        
    ) +
         userId.hashCode
        
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.permissionservice.UserRoles: " + "" + "oid = " + oid + ", " + "roleId = " + roleId + ", " + "userId = " + userId +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.PermissionService.UserRoles@1@1.0")
        
          
          
          
          
            result.putOpt("Oid", this.oid);
          
        
          
          
          
          
            result.putOpt("UserId", this.userId);
          
        
          
          
          
          
            result.putOpt("RoleId", this.roleId);
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              oid = JSONConversions.optional[Int](jobj.opt("Oid"), 0)
          
              userId = jobj.optInt("UserId")
          
              roleId = jobj.optInt("RoleId")
          
        
    }

  
}

object UserRoles {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.PermissionService.UserRoles"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.permissionservice.UserRoles = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.permissionservice.UserRoles")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.permissionservice.UserRoles")

      
        
            val result = new com.trafigura.tradecapture.internal.permissionservice.UserRoles()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(oid: Int = 0, userId: Int = 0, roleId: Int = 0) = {
      val res = new com.trafigura.tradecapture.internal.permissionservice.UserRoles
      
        res.oid = oid
      
        res.userId = userId
      
        res.roleId = roleId
      
      res
    }
  
}
