/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.permissionservice





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._



/**
 user entity
 */


 class User extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var oid:Int = 0
    
    
    

var userId:com.trafigura.tradecapture.internal.permissionservice.UserId = null
    
    
    
    /**
     , :business_key => true
     */

var name:String = null
    
    
    

var disabled:Boolean = false
    
    
    

var deleted:Boolean = false
    
    
    

var neptune:com.trafigura.tradecapture.internal.permissionservice.NeptuneUser = null
    
    
    

var effectivePermissions:List[com.trafigura.tradecapture.internal.permissionservice.Permission] = null
    
    
    

var effectivePermissionsSet:Boolean = false
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.permissionservice.User]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.permissionservice.User]
            that.canEqual(this) && this.deleted == that.deleted && this.disabled == that.disabled && this.effectivePermissions == that.effectivePermissions && this.effectivePermissionsSet == that.effectivePermissionsSet && this.name == that.name && this.neptune == that.neptune && this.oid == that.oid && this.userId == that.userId &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.permissionservice.User]

  override def hashCode = {
    (41 * (41 * (41 * (41 * (41 * (41 * (41 * (41 *  1
    ) +
         deleted.hashCode
        
    ) +
         disabled.hashCode
        
    ) +
         (if (effectivePermissions == null) 0 else effectivePermissions.hashCode) 
    ) +
         effectivePermissionsSet.hashCode
        
    ) +
         (if (name == null) 0 else name.hashCode) 
    ) +
         (if (neptune == null) 0 else neptune.hashCode) 
    ) +
         oid.hashCode
        
    ) +
         (if (userId == null) 0 else userId.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.permissionservice.User: " + "" + "deleted = " + deleted + ", " + "disabled = " + disabled + ", " + "effectivePermissions = " + effectivePermissions + ", " + "effectivePermissionsSet = " + effectivePermissionsSet + ", " + "name = " + name + ", " + "neptune = " + neptune + ", " + "oid = " + oid + ", " + "userId = " + userId +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.PermissionService.User@1@1.0")
        
          
          
          
          
            result.putOpt("Oid", this.oid);
          
        
          
          
          
          
            result.putOpt("UserId", (this.userId) match { case null => null; case o => o.toJson(differentiator) });
          
        
          
          
          
          
            result.putOpt("Name", this.name);
          
        
          
          
          
          
            result.putOpt("Disabled", this.disabled);
          
        
          
          
          
          
            result.putOpt("Deleted", this.deleted);
          
        
          
          
          
          
            result.putOpt("Neptune", (this.neptune) match { case null => null; case o => o.toJson(differentiator) });
          
        
          
          
          
          
            result.putOpt("EffectivePermissions", new org.codehaus.jettison.json.JSONArray(if(this.effectivePermissions == null) new java.util.ArrayList() else java.util.Arrays.asList(this.effectivePermissions.map(t => (t) match { case null => null; case o => o.toJson(differentiator) }).toArray: _*)));
          
        
          
          
          
          
            result.putOpt("EffectivePermissionsSet", this.effectivePermissionsSet);
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              oid = JSONConversions.optional[Int](jobj.opt("Oid"), 0)
          
              userId = (jobj.opt("UserId")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.tradecapture.internal.permissionservice.UserId.fromJson(o, cache))) }
          
              name = JSONConversions.optional[String](jobj.opt("Name"), null)
          
              disabled = JSONConversions.optional[Boolean](jobj.opt("Disabled"), false)
          
              deleted = JSONConversions.optional[Boolean](jobj.opt("Deleted"), false)
          
              neptune = (jobj.opt("Neptune")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.tradecapture.internal.permissionservice.NeptuneUser.fromJson(o, cache))) }
          
              effectivePermissions = JSONConversions.optionalList(jobj.opt("EffectivePermissions"), x => (x) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.tradecapture.internal.permissionservice.Permission.fromJson(o, cache))) })
          
              effectivePermissionsSet = JSONConversions.optional[Boolean](jobj.opt("EffectivePermissionsSet"), false)
          
        
    }

  
}

object User {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.PermissionService.User"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.permissionservice.User = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.permissionservice.User")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.permissionservice.User")

      
        
            val result = new com.trafigura.tradecapture.internal.permissionservice.User()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(oid: Int = 0, userId: com.trafigura.tradecapture.internal.permissionservice.UserId = null, name: String = null, disabled: Boolean = false, deleted: Boolean = false, neptune: com.trafigura.tradecapture.internal.permissionservice.NeptuneUser = null, effectivePermissions: List[com.trafigura.tradecapture.internal.permissionservice.Permission] = null, effectivePermissionsSet: Boolean = false) = {
      val res = new com.trafigura.tradecapture.internal.permissionservice.User
      
        res.oid = oid
      
        res.userId = userId
      
        res.name = name
      
        res.disabled = disabled
      
        res.deleted = deleted
      
        res.neptune = neptune
      
        res.effectivePermissions = effectivePermissions
      
        res.effectivePermissionsSet = effectivePermissionsSet
      
      res
    }
  
}
