/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.permissionservice





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class UserGroups extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var oid:Int = 0
    
    
    

var userId:Int = 0
    
    
    

var groupId:Int = 0
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.permissionservice.UserGroups]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.permissionservice.UserGroups]
            that.canEqual(this) && this.groupId == that.groupId && this.oid == that.oid && this.userId == that.userId &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.permissionservice.UserGroups]

  override def hashCode = {
    (41 * (41 * (41 *  1
    ) +
         groupId.hashCode
        
    ) +
         oid.hashCode
        
    ) +
         userId.hashCode
        
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.permissionservice.UserGroups: " + "" + "groupId = " + groupId + ", " + "oid = " + oid + ", " + "userId = " + userId +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.PermissionService.UserGroups@1@1.0")
        
          
          
          
          
            result.putOpt("Oid", this.oid);
          
        
          
          
          
          
            result.putOpt("UserId", this.userId);
          
        
          
          
          
          
            result.putOpt("GroupId", this.groupId);
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              oid = JSONConversions.optional[Int](jobj.opt("Oid"), 0)
          
              userId = jobj.optInt("UserId")
          
              groupId = jobj.optInt("GroupId")
          
        
    }

  
}

object UserGroups {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.PermissionService.UserGroups"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.permissionservice.UserGroups = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.permissionservice.UserGroups")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.permissionservice.UserGroups")

      
        
            val result = new com.trafigura.tradecapture.internal.permissionservice.UserGroups()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(oid: Int = 0, userId: Int = 0, groupId: Int = 0) = {
      val res = new com.trafigura.tradecapture.internal.permissionservice.UserGroups
      
        res.oid = oid
      
        res.userId = userId
      
        res.groupId = groupId
      
      res
    }
  
}
