/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version .
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_handler.rb

package com.trafigura.exceptions

import com.trafigura.tradinghub.support.{MessageResultListener, MessageProperties}

trait ProcessingExceptionHandler {
  /**
   * Indicates to the handler that a set of com.trafigura.exceptions.ProcessingException objects has arrived and is ready to be processed.
   * Upon completing processing the objects, either acknowledge or reject should be called on the resultListener,
   * allowing transactional transports to release the message in an appropriate manner.
   */
  def onProcessingException(props:MessageProperties, objs:List[com.trafigura.exceptions.ProcessingException], resultListener:MessageResultListener)
}
