/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator_amqp.rb

package com.trafigura.edm.logistics.inventory

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import com.trafigura.tradinghub.services.discovery.ServiceAdvertisement
import org.jboss.resteasy.client._

class AMQPEdmInventoryServiceLocator(ch:ConnectorHolder) extends AbstractServiceLocator[EdmInventoryService](ch) with EdmInventoryServiceLocator {
  def serviceKey = "EdmInventoryService"

  def createProxy(advertisement:ServiceAdvertisement):EdmInventoryService =
    new EdmInventoryServiceResourceProxy(ProxyFactory.create(classOf[EdmInventoryServiceResource], advertisement.address))
}

class AMQPLocatableEdmInventoryService(ch:ConnectorHolder)
  extends LocatableEdmInventoryService(new AMQPEdmInventoryServiceLocator(ch))