/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator.rb

package com.trafigura.edm.logistics.inventory

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import org.jboss.resteasy.client._

import com.trafigura.edm.logistics.inventory._


/**
 * Locator for finding EdmInventoryService instances.
 */
trait EdmInventoryServiceLocator {
  /**
   * Provides a proxy for the given operation to run.
   */
  def proxy:EdmInventoryService
}

class LocatableEdmInventoryService(val locator:EdmInventoryServiceLocator) extends EdmInventoryService {
  
    def getInventoryById(inventoryId: Int): com.trafigura.edm.logistics.inventory.LogisticsInventoryResponse =
      locator.proxy.getInventoryById(inventoryId)
  
    def getInventoryTreeByPurchaseQuotaId(quotaId: String): com.trafigura.edm.logistics.inventory.LogisticsInventoryResponse =
      locator.proxy.getInventoryTreeByPurchaseQuotaId(quotaId)
  
    def getInventoryByGroupCompanyId(groupCompanyMappingCode: String): com.trafigura.edm.logistics.inventory.LogisticsInventoryResponse =
      locator.proxy.getInventoryByGroupCompanyId(groupCompanyMappingCode)
  
}