package maker.project

import com.typesafe.zinc.Compiler
import java.io.{ File, FileWriter, Writer }
import maker.MakerProps
import org.apache.commons.io.FileUtils

class EnsimeGenerator(props: MakerProps) {
  def generateModules(root: File, name: String, modules: List[Module]): Unit = {
    val writer = new FileWriter(new File(root, ".ensime"))
    try {
      writer.append(";; Generated by Maker\n\n")
      writer.append("(\n")
      writer.append("  :root-dir \"" + root.getAbsolutePath + "\"\n")
      writer.append("  :name \"" + name + "\"\n")

      // Java and Scala sources are shared between all modules
      writer.append("  :reference-source-roots (\n")
      writer.append("    \"" + new File(props.JavaHome(), "src.zip").getAbsolutePath + "\"\n")
      writer.append("    \"" + props.ProjectScalaLibrarySourceJar().getAbsolutePath + "\"\n")
      writer.append("  )\n")

      writer.append("  :subprojects (\n")

      modules.foreach(appendModule(writer, _))

      writer.append(
        """  )
          |)
          |""".stripMargin)
    } finally writer.close()
  }

  private def appendModule(writer: Writer, module: Module): Unit = {
    writer.append("    (\n")
    writer.append("      :name \"" + module.name + "\"\n")
    writer.append("      :module-name \"" + module.name + "\"\n")

    writer.append("      :depends-on-modules (\n")
    module.immediateUpstreamModules.foreach { dep =>
      writer.append("        \"" + dep.name + "\"\n")
    }
    writer.append("      )\n")

    writer.append("      :compile-deps (\n")
    def appendDeps(m: Module): Unit = {
      m.managedJars.foreach { dep =>
        writer.append("        \"" + dep.getAbsolutePath + "\"\n")
      }
    }
    appendDeps(module)
    writer.append("      )\n")

    writer.append("      :reference-source-roots (\n")
    def appendDepRefSrcs(m: Module): Unit = {
      if (m.managedLibSourceDir.exists)
        m.managedLibSourceDir.list.filter{ f =>
          f.endsWith(".jar") || f.endsWith(".zip")
        } foreach { dep =>
          val from = new File(m.managedLibSourceDir, dep)
          writer.append("        \"" + from.getAbsolutePath + "\"\n")
        }
    }
    appendDepRefSrcs(module)
    writer.append("      )\n")

    writer.append("      :source-roots (\n")
    writer.append("        \"" + module.sourceDir.getAbsolutePath + "\"\n")
    writer.append("        \"" + module.testSourceDir.getAbsolutePath + "\"\n")
    writer.append("      )\n")

    writer.append("      :target \"" + module.outputDir.getAbsolutePath + "\"\n")
    writer.append("      :test-target \"" + module.testOutputFile.getAbsolutePath + "\"\n")

    writer.append("    )\n")
  }
}
