/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version .
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_receiver_amqp.rb

package com.trafigura.shared.events

import com.rabbitmq.messagepatterns.unicast.ReceivedMessage
import com.trafigura.tradinghub.support._
import org.codehaus.jettison.json.JSONArray

/**
 * Receiver that connects to an AMQP broker and receives incoming com.trafigura.shared.events.Event entities.
 */
class AMQPEventReceiver(ch:ConnectorHolder, val appName:String, val handler:com.trafigura.shared.events.EventHandler)
    extends AbstractAMQPReceiver(ch) {

  def queueName = "Trafigura.Event." + appName
  def onMessage(msg:ReceivedMessage, resultListener: MessageResultListener) {
    val payload = new String(msg.getBody, "UTF-8")
    val props = new AMQPMessageProperties(msg)
    val jsonArr = new JSONArray(payload)
    val objs = (0 until jsonArr.length).toList.map(idx => com.trafigura.shared.events.Event.fromJson(jsonArr.getJSONObject(idx), new DeserialisationHelper))
    handler.onEvent(props, objs, resultListener)
  }
}
