/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version .
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_dispatcher.rb

package com.trafigura.tradecapture.internal.refinedmetal

/**
 * Dispatcher that will send messages of the given type via the messaging transport.
 */
trait AmendmentParametersDispatcher {
  /**
   * Dispatches a single com.trafigura.tradecapture.internal.refinedmetal.AmendmentParameters.
   */
  def dispatchAmendmentParameters(obj:com.trafigura.tradecapture.internal.refinedmetal.AmendmentParameters):Unit = dispatchAmendmentParameters(List(obj), Map[String, String]())

  /**
   * Dispatches a single com.trafigura.tradecapture.internal.refinedmetal.AmendmentParameters.
   */
  def dispatchAmendmentParameters(obj:com.trafigura.tradecapture.internal.refinedmetal.AmendmentParameters, metadata:Map[String, String]):Unit =
    dispatchAmendmentParameters(List(obj), metadata)

  /**
   * Dispatches a list of com.trafigura.tradecapture.internal.refinedmetal.AmendmentParameters entities. These entities will be sent as a single
   * batch, and will be received by a corresponding receiver in the same grouping.
   */
  def dispatchAmendmentParameters(objs:List[com.trafigura.tradecapture.internal.refinedmetal.AmendmentParameters]):Unit =
    dispatchAmendmentParameters(objs, Map[String, String]())

  /**
   * Dispatches a list of com.trafigura.tradecapture.internal.refinedmetal.AmendmentParameters entities. These entities will be sent as a single
   * batch, and will be received by a corresponding receiver in the same grouping.
   */
  def dispatchAmendmentParameters(objs:List[com.trafigura.tradecapture.internal.refinedmetal.AmendmentParameters], metadata:Map[String, String]):Unit
}
