/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.refinedmetal





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class Direction extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var oid:Int = 0
    
    
    

var guid:GUID = null
    
    
    

var expired:Boolean = false
    
    
    

var description:String = null
    
    
    

var code:String = null
    
    
    

var purchase:Boolean = false
    
    
    

var refDataBaseId:Int = 0
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Direction]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Direction]
            that.canEqual(this) && this.code == that.code && this.description == that.description && this.expired == that.expired && this.guid == that.guid && this.oid == that.oid && this.purchase == that.purchase && this.refDataBaseId == that.refDataBaseId &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Direction]

  override def hashCode = {
    (41 * (41 * (41 * (41 * (41 * (41 * (41 *  1
    ) +
         (if (code == null) 0 else code.hashCode) 
    ) +
         (if (description == null) 0 else description.hashCode) 
    ) +
         expired.hashCode
        
    ) +
         (if (guid == null) 0 else guid.hashCode) 
    ) +
         oid.hashCode
        
    ) +
         purchase.hashCode
        
    ) +
         refDataBaseId.hashCode
        
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.refinedmetal.Direction: " + "" + "code = " + code + ", " + "description = " + description + ", " + "expired = " + expired + ", " + "guid = " + guid + ", " + "oid = " + oid + ", " + "purchase = " + purchase + ", " + "refDataBaseId = " + refDataBaseId +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.RefinedMetal.Direction@1@1.0")
        
          
          
          
          
            result.putOpt("Oid", this.oid);
          
        
          
          
          
          
            result.putOpt("Guid", if (this.guid == null) null else this.guid.toJson);
          
        
          
          
          
          
            result.putOpt("Expired", this.expired);
          
        
          
          
          
          
            result.putOpt("Description", this.description);
          
        
          
          
          
          
            result.putOpt("Code", this.code);
          
        
          
          
          
          
            result.putOpt("Purchase", this.purchase);
          
        
          
          
          
          
            result.putOpt("RefDataBaseId", this.refDataBaseId);
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              oid = JSONConversions.optional[Int](jobj.opt("Oid"), 0)
          
              guid = if (jobj.opt("Guid") == null) null else GUID(JSONConversions.optional[String](jobj.opt("Guid"), null))
          
              expired = JSONConversions.optional[Boolean](jobj.opt("Expired"), false)
          
              description = JSONConversions.optional[String](jobj.opt("Description"), null)
          
              code = JSONConversions.optional[String](jobj.opt("Code"), null)
          
              purchase = JSONConversions.optional[Boolean](jobj.opt("Purchase"), false)
          
              refDataBaseId = jobj.optInt("RefDataBaseId")
          
        
    }

  
}

object Direction {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.RefinedMetal.Direction"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.refinedmetal.Direction = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.refinedmetal.Direction")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.refinedmetal.Direction")

      
        
            val result = new com.trafigura.tradecapture.internal.refinedmetal.Direction()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  
  val PurchaseDir = 1
  
  val SaleDir = 2
  

  
    def apply(oid: Int = 0, guid: GUID = null, expired: Boolean = false, description: String = null, code: String = null, purchase: Boolean = false, refDataBaseId: Int = 0) = {
      val res = new com.trafigura.tradecapture.internal.refinedmetal.Direction
      
        res.oid = oid
      
        res.guid = guid
      
        res.expired = expired
      
        res.description = description
      
        res.code = code
      
        res.purchase = purchase
      
        res.refDataBaseId = refDataBaseId
      
      res
    }
  
}
