/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.refinedmetal





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class Guarantee extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var amount:com.trafigura.edm.shared.types.Quantity = null
    
    
    

var requiredBy:org.joda.time.LocalDate = null
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Guarantee]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Guarantee]
            that.canEqual(this) && this.amount == that.amount && this.requiredBy == that.requiredBy &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Guarantee]

  override def hashCode = {
    (41 * (41 *  1
    ) +
         (if (amount == null) 0 else amount.hashCode) 
    ) +
         (if (requiredBy == null) 0 else requiredBy.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.refinedmetal.Guarantee: " + "" + "amount = " + amount + ", " + "requiredBy = " + requiredBy +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.RefinedMetal.Guarantee@1@1.0")
        
          
          
          
          
            result.putOpt("Amount", (this.amount) match { case null => null; case o => o.toJson(differentiator) });
          
        
          
          
          
          
            result.putOpt("RequiredBy", JSONConversions.optionalDateToJSON(this.requiredBy));
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              amount = (jobj.opt("Amount")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.edm.shared.types.Quantity.fromJson(o, cache))) }
          
              requiredBy = JSONConversions.optionalDate(jobj.opt("RequiredBy"))
          
        
    }

  
}

object Guarantee {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.RefinedMetal.Guarantee"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.refinedmetal.Guarantee = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.refinedmetal.Guarantee")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.refinedmetal.Guarantee")

      
        
            val result = new com.trafigura.tradecapture.internal.refinedmetal.Guarantee()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(amount: com.trafigura.edm.shared.types.Quantity = null, requiredBy: org.joda.time.LocalDate = null) = {
      val res = new com.trafigura.tradecapture.internal.refinedmetal.Guarantee
      
        res.amount = amount
      
        res.requiredBy = requiredBy
      
      res
    }
  
}
