/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.refinedmetal





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class PaymentDate extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var oid:Int = 0
    
    
    
    /**
     field 'referenceEvent',               :'TradeEvent'
     */

var daysOffset:Int = 0
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.PaymentDate]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.PaymentDate]
            that.canEqual(this) && this.daysOffset == that.daysOffset && this.oid == that.oid &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.PaymentDate]

  override def hashCode = {
    (41 * (41 *  1
    ) +
         daysOffset.hashCode
        
    ) +
         oid.hashCode
        
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.refinedmetal.PaymentDate: " + "" + "daysOffset = " + daysOffset + ", " + "oid = " + oid +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.RefinedMetal.PaymentDate@1@1.0")
        
          
          
          
          
            result.putOpt("Oid", this.oid);
          
        
          
          
          
          
            result.putOpt("DaysOffset", this.daysOffset);
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              oid = JSONConversions.optional[Int](jobj.opt("Oid"), 0)
          
              daysOffset = JSONConversions.optional[Int](jobj.opt("DaysOffset"), 0)
          
        
    }

  
}

object PaymentDate {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.RefinedMetal.PaymentDate"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.refinedmetal.PaymentDate = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.refinedmetal.PaymentDate")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.refinedmetal.PaymentDate")

      
        
            val result = new com.trafigura.tradecapture.internal.refinedmetal.PaymentDate()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(oid: Int = 0, daysOffset: Int = 0) = {
      val res = new com.trafigura.tradecapture.internal.refinedmetal.PaymentDate
      
        res.oid = oid
      
        res.daysOffset = daysOffset
      
      res
    }
  
}
