/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.refinedmetal





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class PresentedDocument extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var oid:Int = 0
    
    
    

var documentTypeId:Int = 0
    
    
    

var copy:Boolean = false
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.PresentedDocument]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.PresentedDocument]
            that.canEqual(this) && this.copy == that.copy && this.documentTypeId == that.documentTypeId && this.oid == that.oid &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.PresentedDocument]

  override def hashCode = {
    (41 * (41 * (41 *  1
    ) +
         copy.hashCode
        
    ) +
         documentTypeId.hashCode
        
    ) +
         oid.hashCode
        
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.refinedmetal.PresentedDocument: " + "" + "copy = " + copy + ", " + "documentTypeId = " + documentTypeId + ", " + "oid = " + oid +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.RefinedMetal.PresentedDocument@1@1.0")
        
          
          
          
          
            result.putOpt("Oid", this.oid);
          
        
          
          
          
          
            result.putOpt("DocumentTypeId", this.documentTypeId);
          
        
          
          
          
          
            result.putOpt("Copy", this.copy);
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              oid = JSONConversions.optional[Int](jobj.opt("Oid"), 0)
          
              documentTypeId = jobj.optInt("DocumentTypeId")
          
              copy = JSONConversions.optional[Boolean](jobj.opt("Copy"), false)
          
        
    }

  
}

object PresentedDocument {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.RefinedMetal.PresentedDocument"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.refinedmetal.PresentedDocument = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.refinedmetal.PresentedDocument")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.refinedmetal.PresentedDocument")

      
        
            val result = new com.trafigura.tradecapture.internal.refinedmetal.PresentedDocument()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(oid: Int = 0, documentTypeId: Int = 0, copy: Boolean = false) = {
      val res = new com.trafigura.tradecapture.internal.refinedmetal.PresentedDocument
      
        res.oid = oid
      
        res.documentTypeId = documentTypeId
      
        res.copy = copy
      
      res
    }
  
}
