/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.refinedmetal





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._



/**
 this is really qpMonth
 */


 class PricingOffset extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var oid:Int = 0
    
    
    

var guid:GUID = null
    
    
    

var expired:Boolean = false
    
    
    

var description:String = null
    
    
    

var offset:Int = 0
    
    
    

var mappingCode:String = null
    
    
    

var refDataBaseId:Int = 0
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.PricingOffset]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.PricingOffset]
            that.canEqual(this) && this.description == that.description && this.expired == that.expired && this.guid == that.guid && this.mappingCode == that.mappingCode && this.offset == that.offset && this.oid == that.oid && this.refDataBaseId == that.refDataBaseId &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.PricingOffset]

  override def hashCode = {
    (41 * (41 * (41 * (41 * (41 * (41 * (41 *  1
    ) +
         (if (description == null) 0 else description.hashCode) 
    ) +
         expired.hashCode
        
    ) +
         (if (guid == null) 0 else guid.hashCode) 
    ) +
         (if (mappingCode == null) 0 else mappingCode.hashCode) 
    ) +
         offset.hashCode
        
    ) +
         oid.hashCode
        
    ) +
         refDataBaseId.hashCode
        
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.refinedmetal.PricingOffset: " + "" + "description = " + description + ", " + "expired = " + expired + ", " + "guid = " + guid + ", " + "mappingCode = " + mappingCode + ", " + "offset = " + offset + ", " + "oid = " + oid + ", " + "refDataBaseId = " + refDataBaseId +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.RefinedMetal.PricingOffset@1@1.0")
        
          
          
          
          
            result.putOpt("Oid", this.oid);
          
        
          
          
          
          
            result.putOpt("Guid", if (this.guid == null) null else this.guid.toJson);
          
        
          
          
          
          
            result.putOpt("Expired", this.expired);
          
        
          
          
          
          
            result.putOpt("Description", this.description);
          
        
          
          
          
          
            result.putOpt("Offset", this.offset);
          
        
          
          
          
          
            result.putOpt("MappingCode", this.mappingCode);
          
        
          
          
          
          
            result.putOpt("RefDataBaseId", this.refDataBaseId);
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              oid = JSONConversions.optional[Int](jobj.opt("Oid"), 0)
          
              guid = if (jobj.opt("Guid") == null) null else GUID(JSONConversions.optional[String](jobj.opt("Guid"), null))
          
              expired = JSONConversions.optional[Boolean](jobj.opt("Expired"), false)
          
              description = JSONConversions.optional[String](jobj.opt("Description"), null)
          
              offset = JSONConversions.optional[Int](jobj.opt("Offset"), 0)
          
              mappingCode = JSONConversions.optional[String](jobj.opt("MappingCode"), null)
          
              refDataBaseId = jobj.optInt("RefDataBaseId")
          
        
    }

  
}

object PricingOffset {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.RefinedMetal.PricingOffset"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.refinedmetal.PricingOffset = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.refinedmetal.PricingOffset")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.refinedmetal.PricingOffset")

      
        
            val result = new com.trafigura.tradecapture.internal.refinedmetal.PricingOffset()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(oid: Int = 0, guid: GUID = null, expired: Boolean = false, description: String = null, offset: Int = 0, mappingCode: String = null, refDataBaseId: Int = 0) = {
      val res = new com.trafigura.tradecapture.internal.refinedmetal.PricingOffset
      
        res.oid = oid
      
        res.guid = guid
      
        res.expired = expired
      
        res.description = description
      
        res.offset = offset
      
        res.mappingCode = mappingCode
      
        res.refDataBaseId = refDataBaseId
      
      res
    }
  
}
