/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.refinedmetal





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class Quality extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var gradeId:scala.Option[Int] = None
    
    
    

var shapeId:scala.Option[Int] = None
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Quality]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Quality]
            that.canEqual(this) && this.gradeId == that.gradeId && this.shapeId == that.shapeId &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Quality]

  override def hashCode = {
    (41 * (41 *  1
    ) +
         (if (gradeId == null) 0 else gradeId.hashCode) 
    ) +
         (if (shapeId == null) 0 else shapeId.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.refinedmetal.Quality: " + "" + "gradeId = " + gradeId + ", " + "shapeId = " + shapeId +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.RefinedMetal.Quality@1@1.0")
        
          
          
          
          if(this.gradeId != None) {
            result.putOpt("GradeId", (this.gradeId.get));
          }
        
          
          
          
          if(this.shapeId != None) {
            result.putOpt("ShapeId", (this.shapeId.get));
          }
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              gradeId = (jobj.opt("GradeId")) match {case null => None; case n:Number => Some(n.intValue()); case _ => None}
          
              shapeId = (jobj.opt("ShapeId")) match {case null => None; case n:Number => Some(n.intValue()); case _ => None}
          
        
    }

  
}

object Quality {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.RefinedMetal.Quality"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.refinedmetal.Quality = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.refinedmetal.Quality")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.refinedmetal.Quality")

      
        
            val result = new com.trafigura.tradecapture.internal.refinedmetal.Quality()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(gradeId: scala.Option[Int] = None, shapeId: scala.Option[Int] = None) = {
      val res = new com.trafigura.tradecapture.internal.refinedmetal.Quality
      
        res.gradeId = gradeId
      
        res.shapeId = shapeId
      
      res
    }
  
}
