/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.refinedmetal





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._



/**
 this is the model as used for Release 1 of RMET
A quantity is a number together with a unit of measurement. E.g. 10 MTS
 */


 class Quantity extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var amount:scala.Option[Double] = None
    
    
    

var uomId:scala.Option[Int] = None
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Quantity]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Quantity]
            that.canEqual(this) && this.amount == that.amount && this.uomId == that.uomId &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Quantity]

  override def hashCode = {
    (41 * (41 *  1
    ) +
         (if (amount == null) 0 else amount.hashCode) 
    ) +
         (if (uomId == null) 0 else uomId.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.refinedmetal.Quantity: " + "" + "amount = " + amount + ", " + "uomId = " + uomId +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.RefinedMetal.Quantity@1@1.0")
        
          
          
          
          if(this.amount != None) {
            result.putOpt("Amount", this.amount.getOrElse(null));
          }
        
          
          
          
          if(this.uomId != None) {
            result.putOpt("UomId", (this.uomId.get));
          }
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              amount = (jobj.opt("Amount")) match {case null => None; case n:Number => Some(n.doubleValue()); case _ => None}
          
              uomId = (jobj.opt("UomId")) match {case null => None; case n:Number => Some(n.intValue()); case _ => None}
          
        
    }

  
}

object Quantity {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.RefinedMetal.Quantity"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.refinedmetal.Quantity = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.refinedmetal.Quantity")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.refinedmetal.Quantity")

      
        
            val result = new com.trafigura.tradecapture.internal.refinedmetal.Quantity()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(amount: scala.Option[Double] = None, uomId: scala.Option[Int] = None) = {
      val res = new com.trafigura.tradecapture.internal.refinedmetal.Quantity
      
        res.amount = amount
      
        res.uomId = uomId
      
      res
    }
  
}
