/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from enum_scala.rb

package com.trafigura.tradecapture.internal.refinedmetal

object QuotaIndexEnum {
  def forName(name : String) : QuotaIndexEnum = {
    name match {
      
        case "Cash" => CashQuotaIndex
      
        case "ThreeMonth" => ThreeMonthQuotaIndex
      
        case "AverageOfFour" => AverageOfFourQuotaIndex
      
        case "LowestOfFour" => LowestOfFourQuotaIndex
      
        case "MaxSettlement" => MaxSettlementQuotaIndex
      
        case "ArithmeticAverage" => ArithmeticAverageQuotaIndex
      
        case "VolumeWeightedAverage" => VolumeWeightedAverageQuotaIndex
      
      case _ => null
    }
  }
}
abstract class QuotaIndexEnum() {
  def toJson : String 
}

  object CashQuotaIndex extends QuotaIndexEnum {
    def toJson = "Cash"
  }

  object ThreeMonthQuotaIndex extends QuotaIndexEnum {
    def toJson = "ThreeMonth"
  }

  object AverageOfFourQuotaIndex extends QuotaIndexEnum {
    def toJson = "AverageOfFour"
  }

  object LowestOfFourQuotaIndex extends QuotaIndexEnum {
    def toJson = "LowestOfFour"
  }

  object MaxSettlementQuotaIndex extends QuotaIndexEnum {
    def toJson = "MaxSettlement"
  }

  object ArithmeticAverageQuotaIndex extends QuotaIndexEnum {
    def toJson = "ArithmeticAverage"
  }

  object VolumeWeightedAverageQuotaIndex extends QuotaIndexEnum {
    def toJson = "VolumeWeightedAverage"
  }


