/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.refinedmetal





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class RichTranslation extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var reqTranslation:com.trafigura.tradecapture.internal.refinedmetal.Translation = null
    
    
    

var text:String = null
    
    
    

var typeName:String = null
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.RichTranslation]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.RichTranslation]
            that.canEqual(this) && this.reqTranslation == that.reqTranslation && this.text == that.text && this.typeName == that.typeName &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.RichTranslation]

  override def hashCode = {
    (41 * (41 * (41 *  1
    ) +
         (if (reqTranslation == null) 0 else reqTranslation.hashCode) 
    ) +
         (if (text == null) 0 else text.hashCode) 
    ) +
         (if (typeName == null) 0 else typeName.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.refinedmetal.RichTranslation: " + "" + "reqTranslation = " + reqTranslation + ", " + "text = " + text + ", " + "typeName = " + typeName +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.RefinedMetal.RichTranslation@1@1.0")
        
          
          
          
          
            result.putOpt("ReqTranslation", (this.reqTranslation) match { case null => null; case o => o.toJson(differentiator) });
          
        
          
          
          
          
            result.putOpt("Text", this.text);
          
        
          
          
          
          
            result.putOpt("TypeName", this.typeName);
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              reqTranslation = (jobj.opt("ReqTranslation")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.tradecapture.internal.refinedmetal.Translation.fromJson(o, cache))) }
          
              text = JSONConversions.optional[String](jobj.opt("Text"), null)
          
              typeName = JSONConversions.optional[String](jobj.opt("TypeName"), null)
          
        
    }

  
}

object RichTranslation {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.RefinedMetal.RichTranslation"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.refinedmetal.RichTranslation = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.refinedmetal.RichTranslation")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.refinedmetal.RichTranslation")

      
        
            val result = new com.trafigura.tradecapture.internal.refinedmetal.RichTranslation()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(reqTranslation: com.trafigura.tradecapture.internal.refinedmetal.Translation = null, text: String = null, typeName: String = null) = {
      val res = new com.trafigura.tradecapture.internal.refinedmetal.RichTranslation
      
        res.reqTranslation = reqTranslation
      
        res.text = text
      
        res.typeName = typeName
      
      res
    }
  
}
