/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from enum_scala.rb

package com.trafigura.tradecapture.internal.refinedmetal

object TradeWarningWarningTypeEnum {
  def forName(name : String) : TradeWarningWarningTypeEnum = {
    name match {
      
        case "CompletionFailure" => CompletionFailureTradeWarningWarningType
      
      case _ => null
    }
  }
}
abstract class TradeWarningWarningTypeEnum() {
  def toJson : String 
}

  object CompletionFailureTradeWarningWarningType extends TradeWarningWarningTypeEnum {
    def toJson = "CompletionFailure"
  }


