/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from enum_scala.rb

package com.trafigura.tradecapture.internal.refinedmetal

object TradeBlotterQuotaRowVatInvoiceTypeEnum {
  def forName(name : String) : TradeBlotterQuotaRowVatInvoiceTypeEnum = {
    name match {
      
        case "Issued" => IssuedTradeBlotterQuotaRowVatInvoiceType
      
        case "Received" => ReceivedTradeBlotterQuotaRowVatInvoiceType
      
      case _ => null
    }
  }
}
abstract class TradeBlotterQuotaRowVatInvoiceTypeEnum() {
  def toJson : String 
}

  object IssuedTradeBlotterQuotaRowVatInvoiceType extends TradeBlotterQuotaRowVatInvoiceTypeEnum {
    def toJson = "Issued"
  }

  object ReceivedTradeBlotterQuotaRowVatInvoiceType extends TradeBlotterQuotaRowVatInvoiceTypeEnum {
    def toJson = "Received"
  }


