/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.tradecapture.internal.refinedmetal





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class Translation extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var oid:Int = 0
    
    
    

var languageId:Int = 0
    
    
    

var refDataBaseId:Int = 0
    
    
    

var field:String = null
    
    
    

var translated:String = null
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Translation]) {
            val that = r.asInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Translation]
            that.canEqual(this) && this.field == that.field && this.languageId == that.languageId && this.oid == that.oid && this.refDataBaseId == that.refDataBaseId && this.translated == that.translated &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.Translation]

  override def hashCode = {
    (41 * (41 * (41 * (41 * (41 *  1
    ) +
         (if (field == null) 0 else field.hashCode) 
    ) +
         languageId.hashCode
        
    ) +
         oid.hashCode
        
    ) +
         refDataBaseId.hashCode
        
    ) +
         (if (translated == null) 0 else translated.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.tradecapture.internal.refinedmetal.Translation: " + "" + "field = " + field + ", " + "languageId = " + languageId + ", " + "oid = " + oid + ", " + "refDataBaseId = " + refDataBaseId + ", " + "translated = " + translated +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "TradeCapture.Internal.RefinedMetal.Translation@1@1.0")
        
          
          
          
          
            result.putOpt("Oid", this.oid);
          
        
          
          
          
          
            result.putOpt("LanguageId", this.languageId);
          
        
          
          
          
          
            result.putOpt("RefDataBaseId", this.refDataBaseId);
          
        
          
          
          
          
            result.putOpt("Field", this.field);
          
        
          
          
          
          
            result.putOpt("Translated", this.translated);
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              oid = JSONConversions.optional[Int](jobj.opt("Oid"), 0)
          
              languageId = jobj.optInt("LanguageId")
          
              refDataBaseId = jobj.optInt("RefDataBaseId")
          
              field = JSONConversions.optional[String](jobj.opt("Field"), null)
          
              translated = JSONConversions.optional[String](jobj.opt("Translated"), null)
          
        
    }

  
}

object Translation {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "TradeCapture.Internal.RefinedMetal.Translation"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.tradecapture.internal.refinedmetal.Translation = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.tradecapture.internal.refinedmetal.Translation")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.tradecapture.internal.refinedmetal.Translation")

      
        
            val result = new com.trafigura.tradecapture.internal.refinedmetal.Translation()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  
  val TranslatedLength = 255
  

  
    def apply(oid: Int = 0, languageId: Int = 0, refDataBaseId: Int = 0, field: String = null, translated: String = null) = {
      val res = new com.trafigura.tradecapture.internal.refinedmetal.Translation
      
        res.oid = oid
      
        res.languageId = languageId
      
        res.refDataBaseId = refDataBaseId
      
        res.field = field
      
        res.translated = translated
      
      res
    }
  
}
