package starling.schemaevolution

class Patch134_RemoveNeptuneMarketDataSet_OldSchema extends Patch133_DontStoreMarketDataAgainstTransientNames_OldSchema
class Patch134_RemoveNeptuneMarketDataSet_NewSchema extends Patch133_DontStoreMarketDataAgainstTransientNames_NewSchema