package starling.schemaevolution

class Patch129_RemoveNeptuneMarketDataSet_OldSchema extends Patch128_DontStoreMarketDataAgainstTransientNames_OldSchema
class Patch129_RemoveNeptuneMarketDataSet_NewSchema extends Patch128_DontStoreMarketDataAgainstTransientNames_NewSchema