package starling.schemaevolution

import starling.services.StarlingInit
import starling.richdb.RichDB
import system.Patch
import starling.marketdata._
import starling.quantity.UOM._
import starling.quantity.Quantity
import starling.daterange.{ObservationPoint, Day}
import starling.db.{MarketDataEntry, MarketDataSet, DBWriter}
import starling.market._

class Patch152_BenchmarkDataChinaNoDayUpdate1 extends Patch {

  override def requiresRestart = true // because this patch modifies markets which may have been read already.

  protected def runPatch(starlingInit: StarlingInit, starling: RichDB, writer: DBWriter) = {
    val patchUtil = MarketDataPatchUtil(starling, writer)
    patchUtil.deleteMarketData(true, MarketDataTypeName("CountryBenchmark"))
    val entries = 
        List(
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("LEAD1")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("1L")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("3L")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("LEAD1")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("INGOT")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("3L")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(0.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("AAA"), GradeCode("INGOT")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("AAA"), GradeCode("3L")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("1L")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("AAA"), GradeCode("LEAD1")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("AAA"), GradeCode("1L")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("INGOT")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Lead), CountryBenchmarkData(Map((NeptuneCountryCode("AU1"), GradeCode("1L")) -> Map(Day.parse("21Nov2011") -> Quantity(25.025, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("XHK"), GradeCode("SA00")) -> Map(Day.parse("01Nov2011") -> Quantity(23.456, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("AAA"), GradeCode("NSA01")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(200.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("AAW"), GradeCode("NSA01")) -> Map(Day.parse("16Dec2011") -> Quantity(20.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(100.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("AAA"), GradeCode("NSA00")) -> Map(Day.parse("16Dec2011") -> Quantity(80.0, CNY/MT), Day.parse("17Nov2011") -> Quantity(250.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("XTJ"), GradeCode("SA00")) -> Map(Day.parse("16Nov2011") -> Quantity(300.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(100.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("XTW"), GradeCode("NSA00")) -> Map(Day.parse("03Nov2011") -> Quantity(1000.0, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("XIT"), GradeCode("AA")) -> Map(Day.parse("23Nov2011") -> Quantity(1234.0, USD/MT), Day.parse("18Nov2011") -> Quantity(1234.0, USD/MT), Day.parse("01Nov2011") -> Quantity(1233.0, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("NSA01")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(200.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("XTJ"), GradeCode("NSA01")) -> Map(Day.parse("16Nov2011") -> Quantity(200.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("AAA"), GradeCode("SA00")) -> Map(Day.parse("16Nov2011") -> Quantity(300.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(100.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("NSA00")) -> Map(Day.parse("16Dec2011") -> Quantity(30.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(150.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("AAX"), GradeCode("SA00")) -> Map(Day.parse("16Nov2011") -> Quantity(200.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("NSA00")) -> Map(Day.parse("16Nov2011") -> Quantity(250.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(80.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("AAX"), GradeCode("NSA01")) -> Map(Day.parse("16Nov2011") -> Quantity(100.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(20.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("AAX"), GradeCode("NSA00")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(200.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("AAW"), GradeCode("NSA00")) -> Map(Day.parse("16Dec2011") -> Quantity(30.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(150.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("XIT"), GradeCode("NSA00")) -> Map(Day.parse("03Nov2011") -> Quantity(9000.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("SA00")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(200.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("NSA01")) -> Map(Day.parse("16Dec2011") -> Quantity(20.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(100.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("SA00")) -> Map(Day.parse("16Nov2011") -> Quantity(300.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(100.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("HMC"), GradeCode("A0")) -> Map(Day.parse("18Nov2011") -> Quantity(12.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("AAW"), GradeCode("SA00")) -> Map(Day.parse("16Nov2011") -> Quantity(200.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Aluminium), CountryBenchmarkData(Map((NeptuneCountryCode("XTJ"), GradeCode("NSA00")) -> Map(Day.parse("16Dec2011") -> Quantity(80.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(250.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(AluminiumAlloy), CountryBenchmarkData(Map((NeptuneCountryCode("XIT"), GradeCode("AA")) -> Map(Day.parse("01Nov2011") -> Quantity(1000.0, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("SHGC")) -> Map(Day.parse("16Mar2012") -> Quantity(-50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(-100.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("NSSC")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(150.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("STAND")) -> Map(Day.parse("16Dec2011") -> Quantity(100.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(250.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XTW"), GradeCode("STAND")) -> Map(Day.parse("01Jan2011") -> Quantity(1000.0, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XHK"), GradeCode("#1SCP")) -> Map(Day.parse("01Nov2011") -> Quantity(100.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("OC")) -> Map(Day.parse("16Dec2011") -> Quantity(-600.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(-600.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("CHB"), GradeCode("STAND")) -> Map(Day.parse("06Nov2011") -> Quantity(3525.0, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("STAND")) -> Map(Day.parse("16Nov2011") -> Quantity(-50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(0.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XHK"), GradeCode("#2SCP")) -> Map(Day.parse("01Nov2011") -> Quantity(34.12, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("OC")) -> Map(Day.parse("16Nov2011") -> Quantity(-600.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(-600.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XTJ"), GradeCode("SHGC")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(200.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XTJ"), GradeCode("STAND")) -> Map(Day.parse("16Dec2011") -> Quantity(100.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(250.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("SHSCU")) -> Map(Day.parse("16Dec2011") -> Quantity(-100.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(-150.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("OFFG")) -> Map(Day.parse("16Dec2011") -> Quantity(-600.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XIT"), GradeCode("#1SCP")) -> Map(Day.parse("18Nov2011") -> Quantity(150.45, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XIT"), GradeCode("STAND")) -> Map(Day.parse("03Nov2011") -> Quantity(1000.0, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XTJ"), GradeCode("OC")) -> Map(Day.parse("16Nov2011") -> Quantity(-600.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(-600.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("XTJ"), GradeCode("SHSCU")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(150.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Copper), CountryBenchmarkData(Map((NeptuneCountryCode("STO"), GradeCode("#2SCP")) -> Map(Day.parse("24Nov2011") -> Quantity(13.4, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Nickel), CountryBenchmarkData(Map((NeptuneCountryCode("XTW"), GradeCode("FPC")) -> Map(Day.parse("03Nov2011") -> Quantity(134.34, EUR/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Nickel), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("FPC")) -> Map(Day.parse("16Nov2011") -> Quantity(1282.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(1282.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("S0Z")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XTJ"), GradeCode("S0Z")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XTJ"), GradeCode("NS0Z")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XQD"), GradeCode("NS0Z")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("NS0Z")) -> Map(Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XQD"), GradeCode("S0Z")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("S0Z")) -> Map(Day.parse("16Dec2011") -> Quantity(-250.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(150.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XQD"), GradeCode("NS1ZN")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XIT"), GradeCode("CGG")) -> Map(Day.parse("18Nov2011") -> Quantity(50.0, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XTJ"), GradeCode("NS1ZN")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("CWU"), GradeCode("S0Z")) -> Map(Day.parse("16Nov2011") -> Quantity(150.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("NS1ZN")) -> Map(Day.parse("16Dec2011") -> Quantity(-250.0, CNY/MT), Day.parse("16Nov2011") -> Quantity(150.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XHK"), GradeCode("NS0Z")) -> Map(Day.parse("03Nov2011") -> Quantity(11.2, USD/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("CTU"), GradeCode("NS1ZN")) -> Map(Day.parse("16Nov2011") -> Quantity(50.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(50.0, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XSH"), GradeCode("NS0Z")) -> Map(Day.parse("03Nov2012") -> Quantity(11.32, CNY/MT), Day.parse("16Nov2011") -> Quantity(150.0, CNY/MT), Day.parse("16Dec2011") -> Quantity(-250.0, CNY/MT), Day.parse("03Nov2011") -> Quantity(12.2, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Zinc), CountryBenchmarkData(Map((NeptuneCountryCode("XIT"), GradeCode("NS0Z")) -> Map(Day.parse("03Nov2011") -> Quantity(13.4, CNY/MT))))),
          MarketDataEntry(ObservationPoint.RealTime, CountryBenchmarkMarketDataKey(Steel), CountryBenchmarkData(Map((NeptuneCountryCode("XTW"), GradeCode("MESB")) -> Map(Day.parse("01Jan2011") -> Quantity(1000.0, USD/MT)))))
        )

    starlingInit.marketDataStore.save(Map(
      MarketDataSet.ManualMetals  → entries))
  }
}
