/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version .
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_dispatcher_amqp.erb

package com.trafigura.edm.fpc

import com.trafigura.tradinghub.support._

/**
 * Dispatcher for sending com.trafigura.edm.fpc.HedgeRequest entities.
 */
class AMQPHedgeRequestDispatcher(connectorHolder:ConnectorHolder, appName:String)
    extends AbstractAMQPDispatcher(connectorHolder)
    with HedgeRequestDispatcher {

  def exchangeName = "Trafigura.HedgeRequest." + appName

  def dispatchHedgeRequest(objs:List[com.trafigura.edm.fpc.HedgeRequest], metadata:Map[String, String]) {
    val arr = new org.codehaus.jettison.json.JSONArray(java.util.Arrays.asList(objs.map(t => t.toJson()).toArray: _*))
    dispatch(arr.toString.getBytes("UTF-8"), "", metadata)
  }
}
