/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.edm.fpc





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._



/**
 EDM model for initial FPC implementation
Initial fragment of the EDM namespace for the Titan 1.3 FPC implementation
a futures product spec, ref-data source TBD, so month-year + free-form text for now until contract ref-data available
 */


 class ContractMonthName extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var month:org.joda.time.LocalDate = null
    
    
    

var suffix:String = null
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.edm.fpc.ContractMonthName]) {
            val that = r.asInstanceOf[com.trafigura.edm.fpc.ContractMonthName]
            that.canEqual(this) && this.month == that.month && this.suffix == that.suffix &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.edm.fpc.ContractMonthName]

  override def hashCode = {
    (41 * (41 *  1
    ) +
         (if (month == null) 0 else month.hashCode) 
    ) +
         (if (suffix == null) 0 else suffix.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.edm.fpc.ContractMonthName: " + "" + "month = " + month + ", " + "suffix = " + suffix +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "EDM.FPC.ContractMonthName@1@1.0")
        
          
          
          
          
            result.putOpt("Month", JSONConversions.optionalMonthYearToJSON(this.month));
          
        
          
          
          
          
            result.putOpt("Suffix", this.suffix);
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              month = JSONConversions.optionalMonthYear(jobj.opt("Month"))
          
              suffix = JSONConversions.optional[String](jobj.opt("Suffix"), null)
          
        
    }

  
}

object ContractMonthName {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "EDM.FPC.ContractMonthName"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.edm.fpc.ContractMonthName = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.edm.fpc.ContractMonthName")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.edm.fpc.ContractMonthName")

      
        
            val result = new com.trafigura.edm.fpc.ContractMonthName()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  
  val ContractMonthSuffixLength = 50
  

  
    def apply(month: org.joda.time.LocalDate = null, suffix: String = null) = {
      val res = new com.trafigura.edm.fpc.ContractMonthName
      
        res.month = month
      
        res.suffix = suffix
      
      res
    }
  
}
