/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator_amqp.rb

package com.trafigura.tradecapture.internal.refinedmetaltradeservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import com.trafigura.tradinghub.services.discovery.ServiceAdvertisement
import org.jboss.resteasy.client._

class AMQPSyncTradesLocator(ch:ConnectorHolder) extends AbstractServiceLocator[SyncTrades](ch) with SyncTradesLocator {
  def serviceKey = "SyncTrades"

  def createProxy(advertisement:ServiceAdvertisement):SyncTrades =
    new SyncTradesResourceProxy(ProxyFactory.create(classOf[SyncTradesResource], advertisement.address))
}

class AMQPLocatableSyncTrades(ch:ConnectorHolder)
  extends LocatableSyncTrades(new AMQPSyncTradesLocator(ch))