/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator_amqp.rb

package com.trafigura.tradecapture.internal.refinedmetaltradeservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import com.trafigura.tradinghub.services.discovery.ServiceAdvertisement
import org.jboss.resteasy.client._

class AMQPGetTradesLocator(ch:ConnectorHolder) extends AbstractServiceLocator[GetTrades](ch) with GetTradesLocator {
  def serviceKey = "GetTrades"

  def createProxy(advertisement:ServiceAdvertisement):GetTrades =
    new GetTradesResourceProxy(ProxyFactory.create(classOf[GetTradesResource], advertisement.address))
}

class AMQPLocatableGetTrades(ch:ConnectorHolder)
  extends LocatableGetTrades(new AMQPGetTradesLocator(ch))