/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from enum_scala.rb

package com.trafigura.tradecapture.internal.refinedmetaltradeservice

object SyncResultResultInfoEnum {
  def forName(name : String) : SyncResultResultInfoEnum = {
    name match {
      
        case "ErrorReadingNeptune" => ErrorReadingNeptuneSyncResultResultInfo
      
        case "ErrorUpdatingTitan" => ErrorUpdatingTitanSyncResultResultInfo
      
        case "UpdatedTitan" => UpdatedTitanSyncResultResultInfo
      
        case "NoDiffWithTitan" => NoDiffWithTitanSyncResultResultInfo
      
        case "CreatedInTitan" => CreatedInTitanSyncResultResultInfo
      
        case "ErrorCreatingInTitan" => ErrorCreatingInTitanSyncResultResultInfo
      
      case _ => null
    }
  }
}
abstract class SyncResultResultInfoEnum() {
  def toJson : String 
}

  object ErrorReadingNeptuneSyncResultResultInfo extends SyncResultResultInfoEnum {
    def toJson = "ErrorReadingNeptune"
  }

  object ErrorUpdatingTitanSyncResultResultInfo extends SyncResultResultInfoEnum {
    def toJson = "ErrorUpdatingTitan"
  }

  object UpdatedTitanSyncResultResultInfo extends SyncResultResultInfoEnum {
    def toJson = "UpdatedTitan"
  }

  object NoDiffWithTitanSyncResultResultInfo extends SyncResultResultInfoEnum {
    def toJson = "NoDiffWithTitan"
  }

  object CreatedInTitanSyncResultResultInfo extends SyncResultResultInfoEnum {
    def toJson = "CreatedInTitan"
  }

  object ErrorCreatingInTitanSyncResultResultInfo extends SyncResultResultInfoEnum {
    def toJson = "ErrorCreatingInTitan"
  }


