/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.edm.physicaltradespecs





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._



/**
 Remarkable similar to UnknownPricingFixation, however that is trade data. The
below is market data and should eventually stop being stored with the trade
 */


 class AveragePricingFixation extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var oid:Int = 0
    
    
    

var oneDayFixingQuantity:com.trafigura.edm.shared.types.Quantity = null
    
    
    

var price:com.trafigura.edm.shared.types.Quantity = null
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.edm.physicaltradespecs.AveragePricingFixation]) {
            val that = r.asInstanceOf[com.trafigura.edm.physicaltradespecs.AveragePricingFixation]
            that.canEqual(this) && this.oid == that.oid && this.oneDayFixingQuantity == that.oneDayFixingQuantity && this.price == that.price &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.edm.physicaltradespecs.AveragePricingFixation]

  override def hashCode = {
    (41 * (41 * (41 *  1
    ) +
         oid.hashCode
        
    ) +
         (if (oneDayFixingQuantity == null) 0 else oneDayFixingQuantity.hashCode) 
    ) +
         (if (price == null) 0 else price.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.edm.physicaltradespecs.AveragePricingFixation: " + "" + "oid = " + oid + ", " + "oneDayFixingQuantity = " + oneDayFixingQuantity + ", " + "price = " + price +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "EDM.PhysicalTradeSpecs.AveragePricingFixation@1@1.0")
        
          
          
          
          
            result.putOpt("Oid", this.oid);
          
        
          
          
          
          
            result.putOpt("OneDayFixingQuantity", (this.oneDayFixingQuantity) match { case null => null; case o => o.toJson(differentiator) });
          
        
          
          
          
          
            result.putOpt("Price", (this.price) match { case null => null; case o => o.toJson(differentiator) });
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              oid = JSONConversions.optional[Int](jobj.opt("Oid"), 0)
          
              oneDayFixingQuantity = (jobj.opt("OneDayFixingQuantity")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.edm.shared.types.Quantity.fromJson(o, cache))) }
          
              price = (jobj.opt("Price")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.edm.shared.types.Quantity.fromJson(o, cache))) }
          
        
    }

  
}

object AveragePricingFixation {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "EDM.PhysicalTradeSpecs.AveragePricingFixation"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.edm.physicaltradespecs.AveragePricingFixation = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.edm.physicaltradespecs.AveragePricingFixation")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.edm.physicaltradespecs.AveragePricingFixation")

      
        
            val result = new com.trafigura.edm.physicaltradespecs.AveragePricingFixation()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(oid: Int = 0, oneDayFixingQuantity: com.trafigura.edm.shared.types.Quantity = null, price: com.trafigura.edm.shared.types.Quantity = null) = {
      val res = new com.trafigura.edm.physicaltradespecs.AveragePricingFixation
      
        res.oid = oid
      
        res.oneDayFixingQuantity = oneDayFixingQuantity
      
        res.price = price
      
      res
    }
  
}
