/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.edm.physicaltradespecs





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._



/**
 Partial averages may have different quantities for each day of averaging
 */


 class PartialAverageDayQuantity extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    
    /**
     field 'oid',                            :integer, :identifier => true
     */

var date:org.joda.time.LocalDate = null
    
    
    

var quantity:com.trafigura.edm.shared.types.Quantity = null
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity]) {
            val that = r.asInstanceOf[com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity]
            that.canEqual(this) && this.date == that.date && this.quantity == that.quantity &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity]

  override def hashCode = {
    (41 * (41 *  1
    ) +
         (if (date == null) 0 else date.hashCode) 
    ) +
         (if (quantity == null) 0 else quantity.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity: " + "" + "date = " + date + ", " + "quantity = " + quantity +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "EDM.PhysicalTradeSpecs.PartialAverageDayQuantity@1@1.0")
        
          
          
          
          
            result.putOpt("Date", JSONConversions.optionalDateToJSON(this.date));
          
        
          
          
          
          
            result.putOpt("Quantity", (this.quantity) match { case null => null; case o => o.toJson(differentiator) });
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              date = JSONConversions.optionalDate(jobj.opt("Date"))
          
              quantity = (jobj.opt("Quantity")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.edm.shared.types.Quantity.fromJson(o, cache))) }
          
        
    }

  
}

object PartialAverageDayQuantity {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "EDM.PhysicalTradeSpecs.PartialAverageDayQuantity"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity")

      
        
            val result = new com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(date: org.joda.time.LocalDate = null, quantity: com.trafigura.edm.shared.types.Quantity = null) = {
      val res = new com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity
      
        res.date = date
      
        res.quantity = quantity
      
      res
    }
  
}
