/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.edm.physicaltradespecs





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._



/**
 Similar to the more usual monthly average, however
averaging is done over some sub-period
 */


 class PartialAveragePricingSpecification extends com.trafigura.edm.physicaltradespecs.AveragePricingSpecification  {
  


  
    

var market:String = null
    
    
    

var premium:com.trafigura.edm.shared.types.Quantity = null
    
    
    
    /**
     Note that the sum of quantities in this map should equal the pricing spec's own quantity
     */

var dayQtyMap:List[com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity] = null
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.edm.physicaltradespecs.PartialAveragePricingSpecification]) {
            val that = r.asInstanceOf[com.trafigura.edm.physicaltradespecs.PartialAveragePricingSpecification]
            that.canEqual(this) && this.comments == that.comments && this.currency == that.currency && this.dayQtyMap == that.dayQtyMap && this.fixations == that.fixations && this.fxOverrides == that.fxOverrides && this.index == that.index && this.market == that.market && this.ordinal == that.ordinal && this.premium == that.premium && this.quantity == that.quantity &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.edm.physicaltradespecs.PartialAveragePricingSpecification]

  override def hashCode = {
    (41 * (41 * (41 * (41 * (41 * (41 * (41 * (41 * (41 * (41 *  1
    ) +
         (if (comments == null) 0 else comments.hashCode) 
    ) +
         (if (currency == null) 0 else currency.hashCode) 
    ) +
         (if (dayQtyMap == null) 0 else dayQtyMap.hashCode) 
    ) +
         (if (fixations == null) 0 else fixations.hashCode) 
    ) +
         (if (fxOverrides == null) 0 else fxOverrides.hashCode) 
    ) +
         (if (index == null) 0 else index.hashCode) 
    ) +
         (if (market == null) 0 else market.hashCode) 
    ) +
         ordinal.hashCode
        
    ) +
         (if (premium == null) 0 else premium.hashCode) 
    ) +
         (if (quantity == null) 0 else quantity.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.edm.physicaltradespecs.PartialAveragePricingSpecification: " + "" + "comments = " + comments + ", " + "currency = " + currency + ", " + "dayQtyMap = " + dayQtyMap + ", " + "fixations = " + fixations + ", " + "fxOverrides = " + fxOverrides + ", " + "index = " + index + ", " + "market = " + market + ", " + "ordinal = " + ordinal + ", " + "premium = " + premium + ", " + "quantity = " + quantity +  "}"
  }


  
        override def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

    override def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = super.toJson(differentiator);

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "EDM.PhysicalTradeSpecs.PartialAveragePricingSpecification@1@1.0")
        
          
          
          
          
            result.putOpt("Market", this.market);
          
        
          
          
          
          
            result.putOpt("Premium", (this.premium) match { case null => null; case o => o.toJson(differentiator) });
          
        
          
          
          
          
            result.putOpt("DayQtyMap", new org.codehaus.jettison.json.JSONArray(if(this.dayQtyMap == null) new java.util.ArrayList() else java.util.Arrays.asList(this.dayQtyMap.map(t => (t) match { case null => null; case o => o.toJson(differentiator) }).toArray: _*)));
          
        
        return result;
    }

    override def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
            super.loadJson(jobj, cache);
        
        
          
              market = JSONConversions.optional[String](jobj.opt("Market"), null)
          
              premium = (jobj.opt("Premium")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.edm.shared.types.Quantity.fromJson(o, cache))) }
          
              dayQtyMap = JSONConversions.optionalList(jobj.opt("DayQtyMap"), x => (x) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity.fromJson(o, cache))) })
          
        
    }

  
}

object PartialAveragePricingSpecification {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "EDM.PhysicalTradeSpecs.PartialAveragePricingSpecification"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.edm.physicaltradespecs.PartialAveragePricingSpecification = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.edm.physicaltradespecs.PartialAveragePricingSpecification")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.edm.physicaltradespecs.PartialAveragePricingSpecification")

      
        
              v.typeName match {
              
                case _ =>
                  
                     val result = new com.trafigura.edm.physicaltradespecs.PartialAveragePricingSpecification()
                     result.loadJson(jobj, cache)
                     result
                  
            }
        
      
    }

  

  

  
    def apply(market: String = null, premium: com.trafigura.edm.shared.types.Quantity = null, dayQtyMap: List[com.trafigura.edm.physicaltradespecs.PartialAverageDayQuantity] = null) = {
      val res = new com.trafigura.edm.physicaltradespecs.PartialAveragePricingSpecification
      
        res.market = market
      
        res.premium = premium
      
        res.dayQtyMap = dayQtyMap
      
      res
    }
  
}
