/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.edm.physicaltradespecs





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class WeightedPricingSpecification extends com.trafigura.edm.physicaltradespecs.PricingSpecification  {
  


  
    

var wtdSpecs:List[com.trafigura.edm.physicaltradespecs.PriceSpecificationWeighting] = null
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.edm.physicaltradespecs.WeightedPricingSpecification]) {
            val that = r.asInstanceOf[com.trafigura.edm.physicaltradespecs.WeightedPricingSpecification]
            that.canEqual(this) && this.comments == that.comments && this.currency == that.currency && this.fxOverrides == that.fxOverrides && this.ordinal == that.ordinal && this.quantity == that.quantity && this.wtdSpecs == that.wtdSpecs &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.edm.physicaltradespecs.WeightedPricingSpecification]

  override def hashCode = {
    (41 * (41 * (41 * (41 * (41 * (41 *  1
    ) +
         (if (comments == null) 0 else comments.hashCode) 
    ) +
         (if (currency == null) 0 else currency.hashCode) 
    ) +
         (if (fxOverrides == null) 0 else fxOverrides.hashCode) 
    ) +
         ordinal.hashCode
        
    ) +
         (if (quantity == null) 0 else quantity.hashCode) 
    ) +
         (if (wtdSpecs == null) 0 else wtdSpecs.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.edm.physicaltradespecs.WeightedPricingSpecification: " + "" + "comments = " + comments + ", " + "currency = " + currency + ", " + "fxOverrides = " + fxOverrides + ", " + "ordinal = " + ordinal + ", " + "quantity = " + quantity + ", " + "wtdSpecs = " + wtdSpecs +  "}"
  }


  
        override def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

    override def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = super.toJson(differentiator);

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "EDM.PhysicalTradeSpecs.WeightedPricingSpecification@1@1.0")
        
          
          
          
          
            result.putOpt("WtdSpecs", new org.codehaus.jettison.json.JSONArray(if(this.wtdSpecs == null) new java.util.ArrayList() else java.util.Arrays.asList(this.wtdSpecs.map(t => (t) match { case null => null; case o => o.toJson(differentiator) }).toArray: _*)));
          
        
        return result;
    }

    override def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
            super.loadJson(jobj, cache);
        
        
          
              wtdSpecs = JSONConversions.optionalList(jobj.opt("WtdSpecs"), x => (x) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.edm.physicaltradespecs.PriceSpecificationWeighting.fromJson(o, cache))) })
          
        
    }

  
}

object WeightedPricingSpecification {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "EDM.PhysicalTradeSpecs.WeightedPricingSpecification"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.edm.physicaltradespecs.WeightedPricingSpecification = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.edm.physicaltradespecs.WeightedPricingSpecification")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.edm.physicaltradespecs.WeightedPricingSpecification")

      
        
              v.typeName match {
              
                case _ =>
                  
                     val result = new com.trafigura.edm.physicaltradespecs.WeightedPricingSpecification()
                     result.loadJson(jobj, cache)
                     result
                  
            }
        
      
    }

  

  

  
    def apply(wtdSpecs: List[com.trafigura.edm.physicaltradespecs.PriceSpecificationWeighting] = null) = {
      val res = new com.trafigura.edm.physicaltradespecs.WeightedPricingSpecification
      
        res.wtdSpecs = wtdSpecs
      
      res
    }
  
}
