/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.edm.pricingschedules





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class FixedDatesPricingSchedule extends com.trafigura.edm.pricingschedules.NonOptionalPricingSchedule  {
  


  
    

var dates:com.trafigura.edm.common.types.datespecifications.DateRange = null
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.edm.pricingschedules.FixedDatesPricingSchedule]) {
            val that = r.asInstanceOf[com.trafigura.edm.pricingschedules.FixedDatesPricingSchedule]
            that.canEqual(this) && this.dates == that.dates && this.oid == that.oid &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.edm.pricingschedules.FixedDatesPricingSchedule]

  override def hashCode = {
    (41 * (41 *  1
    ) +
         (if (dates == null) 0 else dates.hashCode) 
    ) +
         oid.hashCode
        
    
  }

  override def toString = {
    "{com.trafigura.edm.pricingschedules.FixedDatesPricingSchedule: " + "" + "dates = " + dates + ", " + "oid = " + oid +  "}"
  }


  
        override def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

    override def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = super.toJson(differentiator);

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "EDM.PricingSchedules.FixedDatesPricingSchedule@1@1.0")
        
          
          
          
          
            result.putOpt("Dates", (this.dates) match { case null => null; case o => o.toJson(differentiator) });
          
        
        return result;
    }

    override def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
            super.loadJson(jobj, cache);
        
        
          
              dates = (jobj.opt("Dates")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.edm.common.types.datespecifications.DateRange.fromJson(o, cache))) }
          
        
    }

  
}

object FixedDatesPricingSchedule {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "EDM.PricingSchedules.FixedDatesPricingSchedule"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.edm.pricingschedules.FixedDatesPricingSchedule = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.edm.pricingschedules.FixedDatesPricingSchedule")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.edm.pricingschedules.FixedDatesPricingSchedule")

      
        
              v.typeName match {
              
                case _ =>
                  
                     val result = new com.trafigura.edm.pricingschedules.FixedDatesPricingSchedule()
                     result.loadJson(jobj, cache)
                     result
                  
            }
        
      
    }

  

  

  
    def apply(dates: com.trafigura.edm.common.types.datespecifications.DateRange = null) = {
      val res = new com.trafigura.edm.pricingschedules.FixedDatesPricingSchedule
      
        res.dates = dates
      
      res
    }
  
}
