/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.edm.pricingschedules





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._




 class OptionalPricingSchedule extends com.trafigura.edm.pricingschedules.PricingSchedule  {
  


  





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.edm.pricingschedules.OptionalPricingSchedule]) {
            val that = r.asInstanceOf[com.trafigura.edm.pricingschedules.OptionalPricingSchedule]
            that.canEqual(this) && this.oid == that.oid &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.edm.pricingschedules.OptionalPricingSchedule]

  override def hashCode = {
    (41 *  1
    ) +
         oid.hashCode
        
    
  }

  override def toString = {
    "{com.trafigura.edm.pricingschedules.OptionalPricingSchedule: " + "" + "oid = " + oid +  "}"
  }


  
        override def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

    override def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = super.toJson(differentiator);

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "EDM.PricingSchedules.OptionalPricingSchedule@1@1.0")
        
        return result;
    }

    override def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
            super.loadJson(jobj, cache);
        
        
          
        
    }

  
}

object OptionalPricingSchedule {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "EDM.PricingSchedules.OptionalPricingSchedule"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.edm.pricingschedules.OptionalPricingSchedule = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.edm.pricingschedules.OptionalPricingSchedule")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.edm.pricingschedules.OptionalPricingSchedule")

      
        
              v.typeName match {
              
                case _ =>
                  
                     val result = new com.trafigura.edm.pricingschedules.OptionalPricingSchedule()
                     result.loadJson(jobj, cache)
                     result
                  
            }
        
      
    }

  

  

  
    def apply() = {
      val res = new com.trafigura.edm.pricingschedules.OptionalPricingSchedule
      
      res
    }
  
}
