/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator_amqp.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import com.trafigura.tradinghub.services.discovery.ServiceAdvertisement
import org.jboss.resteasy.client._

class AMQPQPTypeServiceLocator(ch:ConnectorHolder) extends AbstractServiceLocator[QPTypeService](ch) with QPTypeServiceLocator {
  def serviceKey = "QPTypeService"

  def createProxy(advertisement:ServiceAdvertisement):QPTypeService =
    new QPTypeServiceResourceProxy(ProxyFactory.create(classOf[QPTypeServiceResource], advertisement.address))
}

class AMQPLocatableQPTypeService(ch:ConnectorHolder)
  extends LocatableQPTypeService(new AMQPQPTypeServiceLocator(ch))