/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator_amqp.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import com.trafigura.tradinghub.services.discovery.ServiceAdvertisement
import org.jboss.resteasy.client._

class AMQPGradeServiceLocator(ch:ConnectorHolder) extends AbstractServiceLocator[GradeService](ch) with GradeServiceLocator {
  def serviceKey = "GradeService"

  def createProxy(advertisement:ServiceAdvertisement):GradeService =
    new GradeServiceResourceProxy(ProxyFactory.create(classOf[GradeServiceResource], advertisement.address))
}

class AMQPLocatableGradeService(ch:ConnectorHolder)
  extends LocatableGradeService(new AMQPGradeServiceLocator(ch))