/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator_amqp.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import com.trafigura.tradinghub.services.discovery.ServiceAdvertisement
import org.jboss.resteasy.client._

class AMQPSalesTradingRegionServiceLocator(ch:ConnectorHolder) extends AbstractServiceLocator[SalesTradingRegionService](ch) with SalesTradingRegionServiceLocator {
  def serviceKey = "SalesTradingRegionService"

  def createProxy(advertisement:ServiceAdvertisement):SalesTradingRegionService =
    new SalesTradingRegionServiceResourceProxy(ProxyFactory.create(classOf[SalesTradingRegionServiceResource], advertisement.address))
}

class AMQPLocatableSalesTradingRegionService(ch:ConnectorHolder)
  extends LocatableSalesTradingRegionService(new AMQPSalesTradingRegionServiceLocator(ch))