/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator_amqp.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import com.trafigura.tradinghub.services.discovery.ServiceAdvertisement
import org.jboss.resteasy.client._

class AMQPSecurityTermsServiceLocator(ch:ConnectorHolder) extends AbstractServiceLocator[SecurityTermsService](ch) with SecurityTermsServiceLocator {
  def serviceKey = "SecurityTermsService"

  def createProxy(advertisement:ServiceAdvertisement):SecurityTermsService =
    new SecurityTermsServiceResourceProxy(ProxyFactory.create(classOf[SecurityTermsServiceResource], advertisement.address))
}

class AMQPLocatableSecurityTermsService(ch:ConnectorHolder)
  extends LocatableSecurityTermsService(new AMQPSecurityTermsServiceLocator(ch))