/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator_amqp.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import com.trafigura.tradinghub.services.discovery.ServiceAdvertisement
import org.jboss.resteasy.client._

class AMQPPaymentTermsServiceLocator(ch:ConnectorHolder) extends AbstractServiceLocator[PaymentTermsService](ch) with PaymentTermsServiceLocator {
  def serviceKey = "PaymentTermsService"

  def createProxy(advertisement:ServiceAdvertisement):PaymentTermsService =
    new PaymentTermsServiceResourceProxy(ProxyFactory.create(classOf[PaymentTermsServiceResource], advertisement.address))
}

class AMQPLocatablePaymentTermsService(ch:ConnectorHolder)
  extends LocatablePaymentTermsService(new AMQPPaymentTermsServiceLocator(ch))