/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_json.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradecapture.internal.refinedmetal._

import org.codehaus.jettison.json.JSONObject
import com.trafigura.tradinghub.support._

// JSON support for ContractualTermsService

object ContractualTermsServiceJSON extends JSONServiceDispatcher[ContractualTermsService] {
  def serviceName = "TradeCapture.Internal.RefinedMetalReferenceDataService.ContractualTermsService"

  def decodeOperationName(jsonName:String) = {
    jsonName match {
      case "GetContractualTerms" => "GetContractualTerms"
      
    }
  }

  def parseParameters(operation:String, params: JSONObject) = {
    operation match {
      
      case "GetContractualTerms" =>
        
          Map()
        
      
    }
  }

  def invoke(target: ContractualTermsService, operation: String, params: Map[String, Any]): Any = {
    operation match {
      
      case "GetContractualTerms" =>
        target.getContractualTerms()
      
    }
  }

  def addResponse(operation:String, jsonResponse:JSONObject, response:Any) = {
    val differentiator = new SerialisationHelper
    operation match {
      
      case "GetContractualTerms" =>
        jsonResponse.putOpt("result", new org.codehaus.jettison.json.JSONArray(if(response.asInstanceOf[List[com.trafigura.tradecapture.internal.refinedmetal.ContractualTerms]] == null) new java.util.ArrayList() else java.util.Arrays.asList(response.asInstanceOf[List[com.trafigura.tradecapture.internal.refinedmetal.ContractualTerms]].map(t => (t) match { case null => null; case o => o.toJson(differentiator) }).toArray: _*)))
      
    }
  }

  
  def serializeGetContractualTerms(): JSONObject = {
    val differentiator = new SerialisationHelper
    val params = new JSONObject
    
    params
  }
  

  class Proxy(val handler: (String, JSONObject) => JSONObject) extends ContractualTermsService {
  
    def getContractualTerms(): List[com.trafigura.tradecapture.internal.refinedmetal.ContractualTerms] = {
        val request = new JSONObject
        request.put("method", "GetContractualTerms")
        
        var routing = null
        val response = handler(routing, request)
        if (response == null) {
          null.asInstanceOf[List[com.trafigura.tradecapture.internal.refinedmetal.ContractualTerms]]   // Doesn't work well with primitive types, but we should only see null in cases like discover anyway
        } else {
          val cache = new DeserialisationHelper
          JSONConversions.optionalList(response.opt("result"), x => (x) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.tradecapture.internal.refinedmetal.ContractualTerms.fromJson(o, cache))) })
        }
    }
  
  }
}

