/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradecapture.internal.refinedmetal._

import com.trafigura.tradinghub.support._
import org.codehaus.jettison.json.JSONObject
import com.trafigura.tradinghub.support._


/**
 * 
 */

trait CounterpartyService extends ModelService {
  override def serviceNames = super.serviceNames ++ Seq("CounterpartyService")
  override def serviceKeys = super.serviceKeys ++ Seq("CounterpartyService")

  
    def createNonKYCCounterparty(nonKYCCounterParty: com.trafigura.tradecapture.internal.refinedmetal.NonKYCCounterparty): Int
  
    def updateNonKYCCounterparty(nonKYCCounterParty: com.trafigura.tradecapture.internal.refinedmetal.NonKYCCounterparty): Boolean
  
    def getNonKYCCounterparty(oid: Int): com.trafigura.tradecapture.internal.refinedmetal.NonKYCCounterparty
  
    def checkNonKYCCounterpartyExists(oid: Int): Boolean
  
    def checkNonKYCCounterpartyExistsForGroupCompany(oid: Int, groupCompany: com.trafigura.tradecapture.internal.refinedmetal.GroupCompany): Boolean
  
    def getCounterpartyForCode(counterpartyCode: String): List[com.trafigura.tradecapture.internal.refinedmetal.Counterparty]
  
    def getCounterparties(includeTemporary: Boolean): List[com.trafigura.tradecapture.internal.refinedmetal.Counterparty]
  
    def getCounterpartiesForGroupCompany(company: com.trafigura.tradecapture.internal.refinedmetal.GroupCompany): List[com.trafigura.tradecapture.internal.refinedmetal.Counterparty]
  
}
