/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import org.jboss.resteasy.client._

import com.trafigura.tradecapture.internal.refinedmetal._


/**
 * Locator for finding CurrencyService instances.
 */
trait CurrencyServiceLocator {
  /**
   * Provides a proxy for the given operation to run.
   */
  def proxy:CurrencyService
}

class LocatableCurrencyService(val locator:CurrencyServiceLocator) extends CurrencyService {
  
    def getCurrencies(): List[com.trafigura.tradecapture.internal.refinedmetal.Currency] =
      locator.proxy.getCurrencies()
  
}