/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import org.jboss.resteasy.client._

import com.trafigura.tradecapture.internal.refinedmetal._


/**
 * Locator for finding GroupCompanyService instances.
 */
trait GroupCompanyServiceLocator {
  /**
   * Provides a proxy for the given operation to run.
   */
  def proxy:GroupCompanyService
}

class LocatableGroupCompanyService(val locator:GroupCompanyServiceLocator) extends GroupCompanyService {
  
    def getGroupCompanies(): List[com.trafigura.tradecapture.internal.refinedmetal.GroupCompany] =
      locator.proxy.getGroupCompanies()
  
}