/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_locator.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradinghub.support._
import com.trafigura.tradinghub.discovery._
import org.jboss.resteasy.client._

import com.trafigura.tradecapture.internal.refinedmetal._


/**
 * Locator for finding PaymentTermsService instances.
 */
trait PaymentTermsServiceLocator {
  /**
   * Provides a proxy for the given operation to run.
   */
  def proxy:PaymentTermsService
}

class LocatablePaymentTermsService(val locator:PaymentTermsServiceLocator) extends PaymentTermsService {
  
    def getPaymentTerms(): List[com.trafigura.tradecapture.internal.refinedmetal.PaymentTerms] =
      locator.proxy.getPaymentTerms()
  
}