/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service_json.rb

package com.trafigura.tradecapture.internal.refinedmetalreferencedataservice

import com.trafigura.tradecapture.internal.refinedmetal._

import org.codehaus.jettison.json.JSONObject
import com.trafigura.tradinghub.support._

// JSON support for SecurityTermsService

object SecurityTermsServiceJSON extends JSONServiceDispatcher[SecurityTermsService] {
  def serviceName = "TradeCapture.Internal.RefinedMetalReferenceDataService.SecurityTermsService"

  def decodeOperationName(jsonName:String) = {
    jsonName match {
      case "GetSecurityTerms" => "GetSecurityTerms"
      case "GetSecurityTermsForPaymentTerms" => "GetSecurityTermsForPaymentTerms"
      
    }
  }

  def parseParameters(operation:String, params: JSONObject) = {
    operation match {
      
      case "GetSecurityTerms" =>
        
          Map()
        
      
      case "GetSecurityTermsForPaymentTerms" =>
        
          val cache = new DeserialisationHelper
          Map("paymentTerms" -> ((params.opt("PaymentTerms")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.tradecapture.internal.refinedmetal.PaymentTerms.fromJson(o, cache))) }))
        
      
    }
  }

  def invoke(target: SecurityTermsService, operation: String, params: Map[String, Any]): Any = {
    operation match {
      
      case "GetSecurityTerms" =>
        target.getSecurityTerms()
      
      case "GetSecurityTermsForPaymentTerms" =>
        target.getSecurityTermsForPaymentTerms(params("paymentTerms").asInstanceOf[com.trafigura.tradecapture.internal.refinedmetal.PaymentTerms])
      
    }
  }

  def addResponse(operation:String, jsonResponse:JSONObject, response:Any) = {
    val differentiator = new SerialisationHelper
    operation match {
      
      case "GetSecurityTerms" =>
        jsonResponse.putOpt("result", new org.codehaus.jettison.json.JSONArray(if(response.asInstanceOf[List[com.trafigura.tradecapture.internal.refinedmetal.SecurityTerms]] == null) new java.util.ArrayList() else java.util.Arrays.asList(response.asInstanceOf[List[com.trafigura.tradecapture.internal.refinedmetal.SecurityTerms]].map(t => (t) match { case null => null; case o => o.toJson(differentiator) }).toArray: _*)))
      
      case "GetSecurityTermsForPaymentTerms" =>
        jsonResponse.putOpt("result", new org.codehaus.jettison.json.JSONArray(if(response.asInstanceOf[List[com.trafigura.tradecapture.internal.refinedmetal.SecurityTerms]] == null) new java.util.ArrayList() else java.util.Arrays.asList(response.asInstanceOf[List[com.trafigura.tradecapture.internal.refinedmetal.SecurityTerms]].map(t => (t) match { case null => null; case o => o.toJson(differentiator) }).toArray: _*)))
      
    }
  }

  
  def serializeGetSecurityTerms(): JSONObject = {
    val differentiator = new SerialisationHelper
    val params = new JSONObject
    
    params
  }
  
  def serializeGetSecurityTermsForPaymentTerms(paymentTerms: com.trafigura.tradecapture.internal.refinedmetal.PaymentTerms): JSONObject = {
    val differentiator = new SerialisationHelper
    val params = new JSONObject
    
      params.putOpt("PaymentTerms", (paymentTerms) match { case null => null; case o => o.toJson(differentiator) })
    
    params
  }
  

  class Proxy(val handler: (String, JSONObject) => JSONObject) extends SecurityTermsService {
  
    def getSecurityTerms(): List[com.trafigura.tradecapture.internal.refinedmetal.SecurityTerms] = {
        val request = new JSONObject
        request.put("method", "GetSecurityTerms")
        
        var routing = null
        val response = handler(routing, request)
        if (response == null) {
          null.asInstanceOf[List[com.trafigura.tradecapture.internal.refinedmetal.SecurityTerms]]   // Doesn't work well with primitive types, but we should only see null in cases like discover anyway
        } else {
          val cache = new DeserialisationHelper
          JSONConversions.optionalList(response.opt("result"), x => (x) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.tradecapture.internal.refinedmetal.SecurityTerms.fromJson(o, cache))) })
        }
    }
  
    def getSecurityTermsForPaymentTerms(paymentTerms: com.trafigura.tradecapture.internal.refinedmetal.PaymentTerms): List[com.trafigura.tradecapture.internal.refinedmetal.SecurityTerms] = {
        val request = new JSONObject
        request.put("method", "GetSecurityTermsForPaymentTerms")
        
        request.put("params", serializeGetSecurityTermsForPaymentTerms(paymentTerms))
        
        var routing = null
        val response = handler(routing, request)
        if (response == null) {
          null.asInstanceOf[List[com.trafigura.tradecapture.internal.refinedmetal.SecurityTerms]]   // Doesn't work well with primitive types, but we should only see null in cases like discover anyway
        } else {
          val cache = new DeserialisationHelper
          JSONConversions.optionalList(response.opt("result"), x => (x) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.tradecapture.internal.refinedmetal.SecurityTerms.fromJson(o, cache))) })
        }
    }
  
  }
}

