/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service.rb

package com.trafigura.edm.tradeservice

import com.trafigura.edm.tradeservice._
import com.trafigura.edm.trades._

import com.trafigura.tradinghub.support._
import org.codehaus.jettison.json.JSONObject
import com.trafigura.tradinghub.support._


/**
 * 
 */

trait EdmCaptureTrades extends ModelService {
  override def serviceNames = super.serviceNames ++ Seq("EdmCaptureTrades")
  override def serviceKeys = super.serviceKeys ++ Seq("EdmCaptureTrades")

  
    def create(trade: com.trafigura.edm.trades.Trade): com.trafigura.edm.tradeservice.TradeSubmissionResult
  
    def update(trade: com.trafigura.edm.trades.Trade): com.trafigura.edm.tradeservice.TradeSubmissionResult
  
}
