/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_service.rb

package com.trafigura.edm.tradeservice

import com.trafigura.edm.trades._
import com.trafigura.edm.tradeservice._
import com.trafigura.edm.physicaltradespecs._
import com.trafigura.edm.shared.types._

import com.trafigura.tradinghub.support._
import org.codehaus.jettison.json.JSONObject
import com.trafigura.tradinghub.support._


/**
 * this is the interface that returns translated EDM (not real) trades
// The trades are migrated from the refined metal store
 */

trait EdmGetTrades extends ModelService {
  override def serviceNames = super.serviceNames ++ Seq("EdmGetTrades")
  override def serviceKeys = super.serviceKeys ++ Seq("EdmGetTrades")

  
    def getAll(): com.trafigura.edm.tradeservice.TradeResults
  
    def getByGuid(guid: GUID): com.trafigura.edm.trades.Trade
  
    def getQuota(identifier: com.trafigura.edm.shared.types.TitanId): com.trafigura.edm.physicaltradespecs.PhysicalTradeQuota
  
    def get(identifier: com.trafigura.edm.shared.types.TitanId): com.trafigura.edm.trades.Trade
  
}
