/**
 * WARNING: This file was automatically generated by the Trading Hub tooling version 2.15.
 * Any manual changes may be overwritten and lost!
 */


// Generated from model_object_scala.erb

package com.trafigura.edm.tradeservice





import com.trafigura.tradinghub.support._
import scala.collection.JavaConversions._



/**
 // This is the EDM trade service interface definition
 */


 class TradeSubmissionResult extends com.trafigura.tradinghub.support.ModelObject  {
  


  
    

var trade:com.trafigura.edm.trades.Trade = null
    
    
    

var errors:List[String] = null
    
    





  override def equals(o: Any) = o match {
    case r: AnyRef =>
        if (o.isInstanceOf[com.trafigura.edm.tradeservice.TradeSubmissionResult]) {
            val that = r.asInstanceOf[com.trafigura.edm.tradeservice.TradeSubmissionResult]
            that.canEqual(this) && this.errors == that.errors && this.trade == that.trade &&  true
        }
        else false
    case _ => false
  }

  override def canEqual(that : Any) = that.isInstanceOf[com.trafigura.edm.tradeservice.TradeSubmissionResult]

  override def hashCode = {
    (41 * (41 *  1
    ) +
         (if (errors == null) 0 else errors.hashCode) 
    ) +
         (if (trade == null) 0 else trade.hashCode) 
    
  }

  override def toString = {
    "{com.trafigura.edm.tradeservice.TradeSubmissionResult: " + "" + "errors = " + errors + ", " + "trade = " + trade +  "}"
  }


  
         def toJson() : org.codehaus.jettison.json.JSONObject = {
      toJson(new SerialisationHelper)
    }

     def toJson(differentiator: SerialisationHelper) : org.codehaus.jettison.json.JSONObject = {
        var result = new org.codehaus.jettison.json.JSONObject();

        result.put("_node", differentiator.idFor(this))

        result.put("Type", "EDM.TradeService.TradeSubmissionResult@1@1.0")
        
          
          
          
          
            result.putOpt("Trade", (this.trade) match { case null => null; case o => o.toJson(differentiator) });
          
        
          
          
          
          
            result.putOpt("Errors", new org.codehaus.jettison.json.JSONArray(if(this.errors == null) new java.util.ArrayList() else java.util.Arrays.asList(this.errors.map(t => t).toArray: _*)));
          
        
        return result;
    }

     def loadJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper) = {
        
        
          
              trade = (jobj.opt("Trade")) match { case null => null; case o: org.codehaus.jettison.json.JSONObject => cache.objectFor(o).getOrElse(cache.seen(o, com.trafigura.edm.trades.Trade.fromJson(o, cache))) }
          
              errors = JSONConversions.optionalList(jobj.opt("Errors"), x => JSONConversions.optional[String](x, null))
          
        
    }

  
}

object TradeSubmissionResult {
  def version = ModelVersion("1")
  def wireFormatVersion = ModelVersion("1.0")

  
        val jsonTypeName = "EDM.TradeService.TradeSubmissionResult"

    def fromJson(jobj : org.codehaus.jettison.json.JSONObject, cache: DeserialisationHelper = new DeserialisationHelper) : com.trafigura.edm.tradeservice.TradeSubmissionResult = {
      val v = TypeHolder(jobj.optString("Type"))

      v.assertModelVersion(version, "com.trafigura.edm.tradeservice.TradeSubmissionResult")
      v.assertWireFormatVersion(wireFormatVersion, "com.trafigura.edm.tradeservice.TradeSubmissionResult")

      
        
            val result = new com.trafigura.edm.tradeservice.TradeSubmissionResult()
            result.loadJson(jobj, cache)
            result
        
      
    }

  

  

  
    def apply(trade: com.trafigura.edm.trades.Trade = null, errors: List[String] = null) = {
      val res = new com.trafigura.edm.tradeservice.TradeSubmissionResult
      
        res.trade = trade
      
        res.errors = errors
      
      res
    }
  
}
